name: Test Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SSH to EC2
        run: ssh -i ${{secrets.EC2_CRED}} ubuntu@${{secrets.EC2_HOST_IP}} "mkdire -p /api/ && cd /api && git clone https://github.com/KrishnenduDakshi2002/Test-Actions-EC2.git && ls -a"
