name: Test Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate key.pem
        run: echo "${{secrets.EC2_CRED}}" | tr -d '\r' > key.pem

      - name: SSH to EC2
        run: ssh -i key.pem ubuntu@13.233.35.95 "mkdir -p /api/ && cd /api && git --version"
